#!/bin/sh
#
# Copyright (C) 2017-2023 Savoir-faire Linux, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_cqfd() {
	local cur prev words cword
	_init_completion || return

	case $prev in
	-C|-d|-f)
		_filedir
		return
		;;
	-b)
		local flavors cqfdrc=.cqfdrc
		# before we scan for flavors, see if a cqfdrc name was
		# specified with -f
		for (( i=0; i < ${#words[@]}; i++ )); do
			if [[ ${words[i]} == -f ]]; then
				# eval for tilde expansion
				eval cqfdrc=( "${words[i+1]}" )
			fi
		done

		if [ -e "$cqfdrc" ]; then
			flavors=$(cqfd -f $cqfdrc flavors)
			COMPREPLY=( $(compgen -W "$flavors" -- "$cur") )
		fi
		return
		;;
	init|flavors|release|help)
		return
		;;
	run)
		COMPREPLY=( $(compgen -c "$cur") )
		return
		;;
	esac

	local opts="-C -d -f -b -q -V --version -h --help"
	if [[ "$cur" == -* ]]; then
		COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
		return
	fi

	local cmds="init flavors run release version help"
	COMPREPLY=( $(compgen -W "$cmds $opts" -- "$cur") )
} &&
complete -F _cqfd cqfd
