#!/usr/bin/env bash
#
# cqfd - a tool to wrap commands in controlled Docker containers
#
# Copyright (C) 2015-2025 Savoir-faire Linux, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
set -o pipefail

PROGNAME=$(basename "$0")
VERSION=5.6.1-dev
cqfddir=".cqfd"
cqfdrc=".cqfdrc"
cqfd_user='builder'
cqfd_user_home='/home/builder'
cqfd_user_cwd="$cqfd_user_home/src"
cqfd_shell=${CQFD_SHELL:-/bin/bash}
cqfd_docker_gid="${CQFD_DOCKER_GID:-0}"

## usage() - print usage on stdout
usage() {
	cat <<EOF
Usage: $PROGNAME [OPTIONS] [COMMAND] [COMMAND OPTIONS] [ARGUMENTS]

Options:
    -f <file>            Use file as config file (default .cqfdrc).
    -d <directory>       Use directory as cqfd directory (default .cqfd).
    -C <directory>       Use the specified working directory.
    -b <flavor_name>     Target a specific build flavor.
    -q                   Turn on quiet mode.
    -v or --version      Show version.
    --verbose            Increase the script's verbosity.
    -h or --help         Show this help text.

Commands:
    init                 Initialize project build container.
    exec cmd [args]      Run argument(s) inside build container.
    flavors              List flavors from config file to stdout.
    run [cmdstring]      Run argument(s) inside build container.
    release [cmdstring]  Run argument(s) and release software.
    shell [shargs]       Run shell command inside build container.
    help                 Show this help text.

    By default, the 'run' command is assumed, with the default
    command string configured in your .cqfdrc (see build.command).

Command options for run / release:
    -c <args>            Append args to the default command string.

    cqfd is Copyright (C) 2015-2025 Savoir-faire Linux, Inc.

    This program comes with ABSOLUTELY NO WARRANTY. This is free
    software, and you are welcome to redistribute it under the terms
    of the GNU GPLv3 license; see the LICENSE for more informations.
EOF
}

# parse_ini_config_file()
#   Ref: https://ajdiaz.wordpress.com/2008/02/09/bash-ini-parser/
#        by Andrés J. Díaz - License: MIT
# arg$1: path to ini file
parse_ini_config_file() {
	local ini

	if [ ! -f "$1" ]; then
		die "Unable to find $1 - create it or pick one using 'cqfd -f'"
	fi

	mapfile -t ini <"$1"
	ini=( "${ini[@]//[/\\[}" )                   # escape [
	ini=( "${ini[@]//]/\\]}" )                   # escape ]
	ini=( "${ini[@]//;*/}" )                     # remove comments with ;
	ini=( "${ini[@]/$'\t'=/=}" )                 # remove tabs before =
	ini=( "${ini[@]/=$'\t'/=}" )                 # remove tabs after =
	ini=( "${ini[@]/\ =/=}" )                    # remove space before =
	ini=( "${ini[@]/=\ /=}" )                    # remove space after =
	ini=( "${ini[@]/#\\[/\}$'\n'cfg.section.}" ) # set section prefix
	ini=( "${ini[@]/%\\]/(}" )                   # convert text2function (1)
	ini=( "${ini[@]/%(/()}" )                    # close array parenthesis
	ini=( "${ini[@]/%\)/) {}" )                  # the multiline trick
	ini=( "${ini[@]/%\( \)/\(\) \{}" )           # convert text2function (2)
	ini=( "${ini[@]/%\} \)/\}}" )                # remove extra parenthesis
	ini[0]="${ini[0]/\}/}"                       # remove the first brace
	ini+=( "}" )                                 # add the last brace
	ini=("$(printf "%s\n" "${ini[@]}")")
	if ! eval "${ini[*]}"; then                  # eval the result
		debug "$1: fail to evaluate shell:" "${ini[@]}"
		die "$1: Invalid ini-file!"
	fi
}

## die() - exit when an error occured
# $* messages and variables shown in the error message
die() {
	echo "cqfd: fatal: $*" >&2
	exit 1
}

## debug() - print verbose messages
debug() {
	test -z "$CQFD_DEBUG" || echo "cqfd: debug: $*"
}

# docker_build() - Initialize build container
docker_build() {
	local args=()

	if [ "$quiet" ]; then
		args+=(-q)
	fi

	# Append extra args from the .cqfdrc [build] section
	if [ "$build_docker_build_args" ]; then
		local array
		# shellcheck disable=SC2162
		read -a array <<<"$build_docker_build_args"
		args+=("${array[@]}")
	fi

	# Append extra args from $CQFD_EXTRA_BUILD_ARGS
	if [ "$CQFD_EXTRA_BUILD_ARGS" ]; then
		local array
		# shellcheck disable=SC2162
		read -a array <<<"$CQFD_EXTRA_BUILD_ARGS"
		args+=("${array[@]}")
	fi

	args+=(-t "$docker_img_name")

	if [ -z "$project_build_context" ]; then
		args+=("$(dirname "$dockerfile")")
	else
		args+=("$project_build_context" -f "$dockerfile")
	fi

	debug executing: docker build "${args[@]}"
	docker build "${args[@]}"
}

# image_exists_locally(): checks if image exists in the local image store
# arg$1: the image name to check
image_exists_locally() {
	docker image inspect "$1" &> /dev/null
}

# docker_run() - run command in configured container
# A few implementation details:
#
# - The user executing the command string inside the container is
#   named after $cqfd_user, with the same uid/gid as your user to keep
#   filesystem permissions in sync.
#
# - Your project's source directory is always mapped to $cqfd_user_cwd
#
# - Your ~/.ssh directory is mapped to ~${cqfd_user}/.ssh to provide
#   access to the ssh keys (your build may pull authenticated git
#   repos for example).
#
# arg$1: the command string to execute as $cqfd_user
#
docker_run() {
	local args=(--privileged)

	if ! image_exists_locally "$docker_img_name"; then
		# If custom image name is used, try to pull it before dying
		if [ "$project_custom_img_name" ]; then
			if ! docker pull "$docker_img_name" >& /dev/null; then
				die "Custom image couldn't be pulled, please build/upload it first"
			fi
		else
			die "The docker image doesn't exist, launch 'cqfd init' to create it"
		fi
	fi

	# Append extra args from the .cqfdrc [build] section
	if [ "$build_docker_run_args" ]; then
		local array
		# shellcheck disable=SC2162
		read -a array <<<"$build_docker_run_args"
		args+=("${array[@]}")
	fi

	# Append extra args from $CQFD_EXTRA_RUN_ARGS
	if [ "$CQFD_EXTRA_RUN_ARGS" ]; then
		local array
		# shellcheck disable=SC2162
		read -a array <<<"$CQFD_EXTRA_RUN_ARGS"
		args+=("${array[@]}")
	fi

	args+=(--rm --log-driver=none)

	# always keep stdin open
	args+=(-i)

	# allocate a pty if stdin/err are connected to a tty
	if [ -t 0 ] && [ -t 2 ]; then
		args+=(-t)
	fi

	# If possible, map cqfd_user from the calling user's
	if [ -n "$USER" ]; then
		cqfd_user="$USER"
	fi

	if [ -n "$HOME" ]; then
		cqfd_user_home="$(cd "$HOME"; pwd)"
		cqfd_user_cwd="$(pwd)"
	fi

	# Get the docker gid if the group exists
	if [ "$cqfd_docker_gid" -eq 0 ]; then
		local docker_group
		if IFS=: read -r -a docker_group < <(getent group docker); then
			local docker_users
			IFS=, read -r -a docker_users <<<"${docker_group[3]}"
			for user in "${docker_users[@]}"; do
				if [ "$user" = "$cqfd_user" ]; then
					cqfd_docker_gid="${docker_group[2]}"
					break
				fi
			done
		fi
	fi

	# Display a warning message if using no more supported options
	if [ -n "$CQFD_EXTRA_VOLUMES" ]; then
		die 'Warning: CQFD_EXTRA_VOLUMES is no more supported, use
		CQFD_EXTRA_RUN_ARGS="-v <local_dir>:<container_dir>"'
	fi
	if [ -n "$CQFD_EXTRA_HOSTS" ]; then
		die 'Warning: CQFD_EXTRA_HOSTS is no more supported, use
		CQFD_EXTRA_RUN_ARGS="--add-host <hostname>:<IP_address>"'
	fi
	if [ -n "$CQFD_EXTRA_ENV" ]; then
		die 'Warning: CQFD_EXTRA_ENV is no more supported, use
		CQFD_EXTRA_RUN_ARGS="-e <var_name>=<value>"'
	fi
	if [ -n "$CQFD_EXTRA_PORTS" ]; then
		die 'Warning: CQFD_EXTRA_PORTS is no more supported, use
		CQFD_EXTRA_RUN_ARGS="-p <host_port>:<docker_port>"'
	fi

	# The user may set the user_extra_groups in the .cqfdrc
	# file to add groups to the user in the container.
	local group
	if [ -n "$cqfd_extra_groups" ]; then
		for group in $cqfd_extra_groups; do
			# optional groupd id specified ("name:123")
			if echo "$group" | grep -qE ":[0-9]+$"; then
				CQFD_GROUPS+="${group} "
			else
				id=$(awk -F: "\$1 == \"$group\" { print \$3 }" /etc/group)
				CQFD_GROUPS+="${group}:${id} "
			fi
		done
	fi

	# The user may set the CQFD_EXTRA_RUN_ARGS environment variables
	# to pass custom run arguments to his development container.

	# Set HOME variable for the $cqfd_user, except if it was
	# explicitely set via CQFD_EXTRA_RUN_ARGS
	local home_env_var="HOME=$cqfd_user_home"
	if echo "$CQFD_EXTRA_RUN_ARGS" | grep -qE "(-e[[:blank:]]*|--env[[:blank:]]+)HOME="; then
		home_env_var=""
	fi

	if [ "$home_env_var" ]; then
		args+=(-e "$home_env_var")
	fi

	if [ "$CQFD_NO_USER_SSH_CONFIG" != true ]; then
		args+=(-v "$cqfd_user_home/.ssh:$cqfd_user_home/.ssh")
	fi

	if [ "$CQFD_NO_SSH_CONFIG" != true ]; then
		args+=(-v /etc/ssh:/etc/ssh)
	fi

	if [ "$SSH_AUTH_SOCK" ]; then
		args+=(-v "$SSH_AUTH_SOCK:$cqfd_user_home/.sockets/ssh")
		args+=(-e "SSH_AUTH_SOCK=$cqfd_user_home/.sockets/ssh")
	fi

	if [ "$CQFD_NO_USER_GIT_CONFIG" != true ] && [ -f "$cqfd_user_home/.gitconfig" ]; then
		args+=(--mount "type=bind,src=$cqfd_user_home/.gitconfig,dst=$cqfd_user_home/.gitconfig")
	fi

	if [ "$CQFD_BIND_DOCKER_SOCK" = true ]; then
		args+=(-v /var/run/docker.sock:/var/run/docker.sock)
	fi

	args+=(-v "$cqfd_project_dir:$cqfd_project_dir")

	tmp_launcher=$(make_launcher)
	args+=(-v "$tmp_launcher:/bin/cqfd_launch")

	trap 'rm -f "$tmp_launcher"' EXIT

	args+=("$docker_img_name" cqfd_launch "$1")

	debug executing: docker run "${args[@]}"
	docker run "${args[@]}"
}

# make_archive(): Create a release package.
# Note: the --transform option passed to tar allows to move all the
# specified files at the root of the archive. Therefore, you shouldn't
# include two files with the same name in the list of files to
# archive.
make_archive() {
	local tar_opts
	local files
	local git_short
	local git_long
	local date_rfc3339
	local date_unix

	eval "files=($release_files)"
	if [ -z "${files[*]}" ]; then
		die "No files to archive, check files in $cqfdrc"
	fi

	for file in "${files[@]}"; do
		if [ ! -e "$file" ]; then
			die "Unable to release: unable to find $file"
		fi
	done

	# template the generated archive's filename
	git_short=$(git rev-parse --short HEAD 2>/dev/null || echo unset)
	git_long=$(git rev-parse HEAD 2>/dev/null || echo unset)
	date_rfc3339=$(date +"%Y-%m-%d")
	date_unix=$(date +%s)

	# default name for the archive if not set
	if [ -z "$release_archive" ]; then
		release_archive="%Po-%Pn.tar.xz"
	fi

	# shellcheck disable=SC2001
	release_archive=$(echo "$release_archive" |
		sed -e 's!%%!%!g;
			s!%Gh!'"$git_short"'!g;
			s!%GH!'"$git_long"'!g;
			s!%D3!'"$date_rfc3339"'!g;
			s!%Du!'"$date_unix"'!g;
			s!%Po!'"$project_org"'!g;
			s!%Pn!'"$project_name"'!g;
			s!%Cf!'"$flavor"'!g;')

	# also replace variable names - beware with eval
	eval "release_archive=$release_archive"

	# setting tar_transform=yes will move files to the root of a tar archive
	if [ "$release_transform" = "yes" ]; then
		tar_opts+=('--transform' 's/.*\///g')
	fi

	# setting tar_options=x will pass the options to tar
	if [ "$release_tar_opts" ]; then
		local array
		# shellcheck disable=SC2162
		read -a array <<<"$release_tar_opts"
		tar_opts+=("${array[@]}")
	fi

	# support the following archive formats
	case "$release_archive" in
	*.tar.xz)
		XZ_OPT=-9 tar "${tar_opts[@]}" -cJf \
			"$release_archive" "${files[@]}"
		;;
	*.tar.gz)
		tar "${tar_opts[@]}" -czf \
			"$release_archive" "${files[@]}"
		;;
	*.zip)
		zip -q -9 -r "$release_archive" "${files[@]}"
		;;
	*)
		;;
	esac
}

# make_launcher - generate in-container launcher script
# return: the path to the launcher script on stdout
make_launcher() {
	local tmpfile

	tmpfile=$(mktemp /tmp/tmp.XXXXXX)
	chmod 0755 "$tmpfile"
	cat >"$tmpfile" <<EOF
#!/bin/sh
# create container user to match expected environment

set -e

die() {
	echo "error: \$*" >&2
	exit 1
}

debug() {
	test -z "\$CQFD_DEBUG" || echo "debug: \$*"
}

test_cmd() {
	command -v "\$1" > /dev/null 2>&1
}

test_su_session_command() {
	su --session-command true > /dev/null 2>&1
}

# Check container requirements
test_cmd groupadd || { failed=1 && echo "error: Missing command: groupadd" >&2; }
test_cmd useradd || { failed=1 && echo "error: Missing command: useradd" >&2; }
test_cmd usermod || { failed=1 && echo "error: Missing command: usermod" >&2; }
test_cmd chown || { failed=1 && echo "error: Missing command: chown" >&2; }
test_cmd sudo && has_sudo=1 || test_cmd su ||
	{ failed=1 && echo "error: Missing command: su or sudo" >&2; }
test -n "\$failed" &&
	die "Some dependencies are missing from the container, see above messages."
test_su_session_command && has_su_session_command=1

if ! shell=\$(command -v "$cqfd_shell"); then
	echo "$cqfd_shell: command not found" >&2
	exit 127
fi

# Add the host's user and group to the container, and adjust ownership
groupadd -og "${GROUPS[0]}" -f builders
useradd -s "\$shell" -oN -u "$UID" -g "${GROUPS[0]}" -d "$cqfd_user_home" "$cqfd_user"
mkdir -p "$cqfd_user_home"
chown "$UID:${GROUPS[0]}" "$cqfd_user_home"

# Add specified groups to cqfd_user
for g in ${CQFD_GROUPS}; do
	group=\$(echo "\$g" | cut -d: -f1)
	gid=\$(echo "\$g" | cut -d: -f2)

	if [ -n "\$gid" ]; then
		# create group with provided id ("name:123")
		groupadd -og "\$gid" -f "\$group"
	fi

	usermod -a -G \$group $cqfd_user
done

# Add docker group as cqfd to cqfd_user
if [ "${cqfd_docker_gid:-0}" -gt 0 ]; then
	groupadd -og "$cqfd_docker_gid" -f cqfd
	usermod -a -G cqfd $cqfd_user
fi	

# Run provided command in the working directory
cd "$cqfd_user_cwd"
if [ -n "\$has_sudo" ]; then
	debug "Using \"sudo\" to execute command sh -c \"\$1\" as user \"$cqfd_user\""
	sudo -E -u $cqfd_user sh -c "\$1"
elif [ -n "\$has_su_session_command" ]; then
	debug "Using \"su\" to execute session command \"\$1\" as user \"$cqfd_user\""
	su $cqfd_user -p --session-command "\$1"
else
	debug "Using \"su\" to execute command \"\$1\" as user \"$cqfd_user\""
	su $cqfd_user -p -c "\$1"
fi
EOF
	echo "$tmpfile"
}

# locate_project_dir() - locate directory with .cqfd upwards
# The directory will be printed on stdout, if found.
locate_project_dir() {
	local search_dir="$PWD"

	while [ "$search_dir" != "/" ]; do
		if [ -d "$search_dir"/"$cqfddir" ]; then
			realpath "$search_dir"
			return 0
		fi
		search_dir="$(readlink -f "$search_dir"/..)"
	done

	return 1
}

# config_load() - load build settings from cqfdrc
# $1: optional "flavor" of the build, is a suffix of command.
config_load() {
	if ! cqfd_project_dir=$(locate_project_dir); then
		die ".cqfd directory not found in directory tree"
	fi

	# unless using '-f other_cqfdrc', use base directory located above
	if ! $has_custom_cqfdrc; then
		local cqfdrc_dir="$cqfd_project_dir/"
	fi

	parse_ini_config_file "${cqfdrc_dir}${cqfdrc}"

	# generate dynamically the list of flavors based on the names of shell
	# functions reported by the buildtin:
	#  - the cfg.section. prefix is stripped
	#  - the build and project sections are stripped
	mapfile -t flavors < <(compgen -A function -X '!cfg.section.*')
	flavors=("${flavors[@]/cfg.section./}")
	for i in "${!flavors[@]}"; do
		if [[ "${flavors[$i]}" =~ ^(build|project)$ ]]; then
			unset 'flavors[$i]'
		fi
	done

	cfg.section.project # load the [project] section
	# shellcheck disable=SC2154
	project_org="$org"
	# shellcheck disable=SC2154
	project_name="$name"
	# shellcheck disable=SC2154
	project_build_context="$build_context"
	# shellcheck disable=SC2154
	project_custom_img_name="$custom_img_name"

	cfg.section.build # load the [build] section
	build_flavors="${flavors[*]}"

	# build parameters may be overriden by a flavor defined in the
	# build section's 'flavors' parameter.
	local flavor="$1"
	if [ -n "$flavor" ]; then
		if grep -qw "$flavor" <<< "${flavors[*]}"; then
			cfg.section."$flavor" # load the [$flavor] section
		else
			die "flavor \"$flavor\" not found in flavors list"
		fi
	fi

	# shellcheck disable=SC2154
	build_cmd="$command"
	# shellcheck disable=SC2154
	build_docker_build_args="$docker_build_args"
	# shellcheck disable=SC2154
	build_docker_run_args="$docker_run_args"
	# shellcheck disable=SC2154
	cqfd_extra_groups="$user_extra_groups"
	# shellcheck disable=SC2154
	release_files="$files"
	# shellcheck disable=SC2154
	release_archive="$archive"
	# shellcheck disable=SC2154
	release_transform="$tar_transform"
	# shellcheck disable=SC2154
	release_tar_opts="$tar_options"

	dockerfile="${cqfd_project_dir}/${cqfddir}/${distro:-docker}/Dockerfile"

	if [ -z "$project_org" ] || [ -z "$project_name" ]; then
		die "Please set project.org and project.name in .cqfdrc"
	fi

	if [ ! -f "$dockerfile" ]; then
		die "$dockerfile not found"
	fi

	if [ "$project_custom_img_name" ]; then
		docker_img_name="$project_custom_img_name"
	else
		local format_user
		local dockerfile_hash

		# This will look like cqfd_USER_ORG_NAME_HASH
		# shellcheck disable=SC2001
		format_user=$(echo "$USER" | sed 's/[^0-9a-zA-Z\-]/_/g')
		dockerfile_hash=$(sha256sum "$dockerfile" | cut -b 1-7)
		docker_img_name="cqfd${format_user:+_${format_user}}_${project_org}_${project_name}_${dockerfile_hash}"
	fi

	# Adapt things for a specific container
	if [ -n "$distro" ]; then
		docker_img_name+="_$distro"
	fi
}

has_custom_cqfdrc=false
has_to_release=false
has_alternate_command=false
while [ $# -gt 0 ]; do
	case "$1" in
	help|-h|--help)
		usage
		exit
		;;
	version|-v|--version)
		echo $VERSION
		exit
		;;
	--verbose)
		export CQFD_DEBUG=true
		;;
	init)
		config_load "$flavor"
		docker_build
		exit
		;;
	flavors)
		config_load
		echo "$build_flavors"
		exit
		;;
	-b)
		shift
		flavor="$1"
		;;
	-d)
		shift
		cqfddir="$1"
		;;
	-f)
		shift
		has_custom_cqfdrc=true
		cqfdrc="$1"
		;;
	-C)
		shift
		cd "$1"
		;;
	-q)
		quiet=true
		;;
	exec)
		if [ "$#" -lt 2 ]; then
			die "command exec requires arguments"
		fi
		shift
		config_load "$flavor"
		command_string="${*@Q}"
		docker_run "$command_string"
		exit
		;;
	run|release)
		if [ "$1" = "release" ]; then
			has_to_release=true
		fi

		shift

		# No more args? run default command
		[ "$#" -eq 0 ] && break

		# -c appends following args to the default command
		if [ "$1" = "-c" ]; then
			if [ "$#" -lt 2 ]; then
				die "option -c requires arguments"
			fi

			shift
			break
		fi

		# Run alternate command
		has_alternate_command=true
		break
		;;
	sh|ash|dash|bash|ksh|zsh|csh|tcsh|fish|shell)
		if [ "$1" != "shell" ]; then
			cqfd_shell="$1"
		fi
		shift
		config_load "$flavor"
		command_string="$cqfd_shell"
		if [ "$#" -gt 0 ]; then
			command_string+=" ${*@Q}"
		fi
		docker_run "$command_string"
		exit
		;;
	?*)
		echo "Unknown command: $1" >&2
		usage
		exit 1
		;;
	*)
		# empty or no argument case
		;;
	esac
	shift
done

config_load "$flavor"

if $has_alternate_command; then
	build_cmd="$*"
elif [ -n "$*" ]; then
	build_cmd+=" $*"
fi

if [ -z "$build_cmd" ]; then
	die "No build.command defined in ${cqfdrc}, and no command specified"
fi

docker_run "$build_cmd"

if $has_to_release; then
	make_archive
fi
