= cqfdrc(5)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@savoirfairelinux.com
:lang: en
:man manual: C.Q.F.D. Manual
:man source: C.Q.F.D. Project

== NAME

cqfdrc - project information config file

== DESCRIPTION

The *cqfdrc(5)* file at the root of your project contains the information
required to support project tooling. _samples/dot-cqfdrc_ is an example.

=== The project section

*org*::
	a short, lowercase name for the project’s parent organization.

*name*::
	a short, lowercase name for the project.

Generated Docker images for your project will be named __$org_$name__.

=== The build section

*command*::
	the command (or list of commands) to be executed when cqfd is invoked.
	This string will be passed as an argument to a classical
	bash -c "commands", within the build container, to generate the build
	artefacts.

*files*::
	an optional space-separated list of files generated by the build
	process that we want to include inside a standard release archive.

*archive*::
	the optional name of the release archive generated by cqfd. You can
	include environment variable names, as well as the following template
	marks:
	* *%Gh* - git short hash of last commit
	* *%GH* - git long hash of last commit
	* *%D3* - RFC3339 date (YYYY-MM-DD)
	* *%Cf* - current cqfd flavor name (if any)
	* *%Po* - value of the project.org configuration key
	* *%Pn* - value of the project.name configuration key
	* *%%* - a litteral '%' sign

By default, *cqfd(1)* will generate a release tarball named
__org-name.tar.xz__, where `org' and `name' come from the project's
configuration keys.

*flavors*::
	the list of build flavors (see using flavors in _examples_ section
	below). Each flavor has its own command just like build.command.

== EXAMPLES

=== BASIC

Here is a sample *.cqfdrc(5)* file

    [project]
    org='fooinc'
    name='buildroot'

    [build]
    command='make foobar_defconfig && make && asciidoc README.FOOINC'
    files='README.FOOINC output/images/sdcard.img'
    archive='cqfd-%Gh.tar.xz'

=== USING FLAVORS

In some cases, it may be desirable to build the project using variations of the
build and release methods (for example a debug build). This is made possible in
*cqfd(1)* with the build _flavors_ feature.

In the _.cqfdrc_ file, one or more flavors may be listed in the **[build]**
section, referencing other sections named following flavor's name.

	[debug]
	command='make DEBUG=1'
	files='myprogram Symbols.map'

	[build]
	command='make'
	files='myprogram'
	flavors='debug'

A _flavor_ will typically redefine the keys of the build section: _command_,
_files_, _archive_.

== BUGS REPORTS

Report bugs at *https://github.com/savoirfairelinux/cqfd/issues*

== COPYRIGHT

Copyright (C) 2015-2017 Savoir-faire Linux, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

== SEE ALSO

*cqfd(1)*, *Dockerfile(5)*

== COLOPHON

This page is part of *C.Q.F.D.* project.

*C.Q.F.D.* stands for `Ce qu'il fallait Dockeriser', french for `what needed
to be dockerized'.
