#!/bin/bash

. `dirname $0`/jtest.inc "$1"

jtest_prepare "create a test skeleton in temporary directory"

mkdir -p $TDIR/.cqfd/docker
cp -a ../cqfd $TDIR/.cqfd/
cp -a test_data/. $TDIR/.

cd $TDIR/
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
fi

jtest_prepare "create an empty cqfdrc"

touch $TDIR/.cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
fi

jtest_prepare "create an incomplete cqfdrc"

echo '[project]' >$TDIR/.cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
fi

jtest_result pass

cat $TDIR/cqfdrc-test >$TDIR/.cqfdrc
