#!/bin/bash

. `dirname $0`/jtest.inc "$1"

jtest_prepare "create a test skeleton in temporary directory"

mkdir -p $TDIR/.cqfd/docker
cp -a ../cqfd $TDIR/.cqfd/
cp -a test_data/. $TDIR/.

cd $TDIR/

# running 'cqfd init' should fail, as there's no proper config
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
else
	jtest_result pass
fi

jtest_prepare "create an empty cqfdrc"

# running 'cqfd init' should fail, as there's an empty config
touch $TDIR/.cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
else
	jtest_result pass
fi

jtest_prepare "create an incomplete cqfdrc"

# running 'cqfd init' should fail, as there's an incomplete config
echo '[project]' >$TDIR/.cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
else
	jtest_result pass
fi

# finally, insert a proper testing .cqfdrc
cat $TDIR/cqfdrc-test >$TDIR/.cqfdrc
