#!/bin/bash

. `dirname $0`/jtest.inc "$1"

jtest_prepare "run cqfd init"

cd $TDIR/
$TDIR/.cqfd/cqfd init

jtest_result pass

temp_dir=".cqfd/`mktemp -d`"
cqfdrc_old=`mktemp`
jtest_prepare "init with a nonexisting dockerfile shall fail"
cp .cqfdrc $cqfdrc_old
sed -i -e "s/\[build\]/\[build\]\ndistro='thisshouldfail'/" .cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
else
	jtest_result pass
fi


jtest_prepare "run cqfd init with an other Dockerfile"
sed -i -e "s/thisshouldfail/centos/" .cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi
#restore cqfdrc
mv $cqfdrc_old .cqfdrc

#restore docker image to run on
$TDIR/.cqfd/cqfd init

