#!/bin/bash

. `dirname $0`/jtest.inc "$1"

cd $TDIR/

jtest_prepare "run cqfd init"
if $TDIR/.cqfd/cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi


cqfdrc_old=`mktemp`
jtest_prepare "init with a nonexisting dockerfile shall fail"
cp -f .cqfdrc $cqfdrc_old
sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result fail
else
	jtest_result pass
fi


jtest_prepare "run cqfd init with an other Dockerfile"
sed -i -e "s/thisshouldfail/centos/" .cqfdrc
if $TDIR/.cqfd/cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi
#restore cqfdrc
mv -f $cqfdrc_old .cqfdrc

#restore docker image to run on
$TDIR/.cqfd/cqfd init

