#!/usr/bin/env bash
#
# validate the behavior of help command

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR"/.cqfd/cqfd

################################################################################
# 'cqfd help' shall be an accepted command
################################################################################
jtest_prepare "cqfd help shall exit normally"
TEST=$(mktemp)

if ! "$cqfd" help >"$TEST"; then
	jtest_result fail
	rm -f "$TEST"
else
	jtest_result pass
fi

################################################################################
# 'cqfd help' shall produce a useful help message
################################################################################
jtest_prepare "cqfd help shall produce an help message"
# Those words shall be present in the output
for word in Usage Options Commands; do
	if ! grep -q "^$word:" "$TEST"; then
		jtest_log error "cannot find $word in help message"
		rm -f "$TEST"
		missing=1
	fi
done

if [ "$missing" = "1" ]; then
	jtest_result fail
else
	jtest_result pass
fi

rm -f "$TEST"
