#!/usr/bin/env bash
#
# validate the behavior of version command

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR"/.cqfd/cqfd

################################################################################
# 'cqfd version' shall be an accepted command
################################################################################
jtest_prepare "cqfd version shall exit normally"
TEST=$(mktemp)
if "$cqfd" version >"$TEST"; then
	jtest_result pass
else
	jtest_result fail
	rm -f "$TEST"
fi

################################################################################
# 'cqfd version' shall produce a version message
################################################################################
jtest_prepare "cqfd version shall produce a version string"
if grep -qE "^[0-9.]+(-[a-z]+)?\$" "$TEST"; then
	jtest_result pass
else
	jtest_log error "not a version message"
	cat "$TEST" >&2
	jtest_result fail
fi

rm -f "$TEST"
