#!/usr/bin/env bash
#
# validate the behavior with erroneous usages

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR"/.cqfd/cqfd

################################################################################
# Running cqfd with an unknown argument shall fail
################################################################################
jtest_prepare "run a bad cqfd command-line shall fail"
if ! "$cqfd" invalid_arg_should_fail; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Running cqfd without a .cqfdrc file in the current directory shall fail
################################################################################
jtest_prepare "'cqfd run' with no config file shall fail"
empty_dir=$(mktemp -d)
pushd "$empty_dir" >/dev/null || exit 1
if ! "$cqfd" run true; then
	jtest_result pass
else
	jtest_result fail
fi
popd >/dev/null || exit 1

# cleanup
rm -rf "$empty_dir"
