#!/usr/bin/env bash
#
# validate the behavior of project.build_context

. $(dirname "$0")/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/

################################################################################
# Use a custom Dockerfile
################################################################################
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.missing_dependencies .cqfd/docker/Dockerfile

################################################################################
# Missing all core dependencies for the launch script
################################################################################
jtest_prepare "cqfd fails when the Docker image lacks required commands"
if $cqfd --init && $cqfd; then
	jtest_result fail
else
	jtest_result pass
fi

################################################################################
# Add Bash and the 'shadow' package, which provides useradd, groupadd.
################################################################################
echo 'RUN apk add bash shadow' >> .cqfd/docker/Dockerfile
echo 'ENV CQFD_DEBUG=1' >> .cqfd/docker/Dockerfile

################################################################################
# cqfd should now be happy with the required commands, using su.
################################################################################
jtest_prepare "cqfd with satisfied command requirements, using su"
$cqfd --init && \
    $cqfd true \
	| awk -v rc=1 '/Using "su"/ { rc=0 } 1; END {exit rc}' \
    && jtest_result pass || jtest_result fail

################################################################################
# Install the sudo package.
################################################################################
echo 'RUN apk add sudo' >> .cqfd/docker/Dockerfile

################################################################################
# cqfd should now be happy with the required commands, using sudo
################################################################################
jtest_prepare "cqfd with satisfied command requirements, using sudo"
$cqfd --init && \
    $cqfd true \
	| awk -v rc=1 '/Using "sudo"/ { rc=0 } 1; END {exit rc}' \
    && jtest_result pass || jtest_result fail

################################################################################
# restore initial Dockerfile
################################################################################
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
$cqfd --init
