#!/bin/bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/

################################################################################
# 'cqfd run' passes environment variables to the container when using
# CQFD_EXTRA_ENV
################################################################################
jtest_prepare "run cqfd with extra environment variables"

val1="value-$RANDOM"
val2="value-$RANDOM"

result=$(CQFD_EXTRA_ENV="FOO=$val1 BAR=$val2" $cqfd run 'echo -n $FOO $BAR' | grep value)

if [ "$result" = "$val1 $val2" ]; then
    jtest_result pass
else
    jtest_result fail
fi
