#!/usr/bin/env bash
#
# validate the behavior of run command su and sudo backends

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

################################################################################
# Use a custom Dockerfile with an ancient version of su.
################################################################################
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
echo "FROM ubuntu:16.04" > .cqfd/docker/Dockerfile
echo "ENV CQFD_DEBUG=1" >> .cqfd/docker/Dockerfile

################################################################################
# cqfd run should be happy using su -c.
################################################################################
jtest_prepare "cqfd run with su -c"
if "$cqfd" init && "$cqfd" run true \
	| awk -v rc=1 '/Using "su" to execute command/ { rc=0 } 1; END {exit rc}'; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Use another custom Dockerfile with a recent version of su.
################################################################################
echo "FROM ubuntu:24.04" > .cqfd/docker/Dockerfile
echo "ENV CQFD_DEBUG=1" >> .cqfd/docker/Dockerfile

################################################################################
# cqfd run should be happy using su --session-command.
################################################################################
jtest_prepare "cqfd run with su --session-command"
if "$cqfd" init && "$cqfd" run true \
	| awk -v rc=1 '/Using "su" to execute session command/ { rc=0 } 1; END {exit rc}'; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Install the sudo package.
################################################################################
echo "ENV DEBIAN_FRONTEND noninteractive" >> .cqfd/docker/Dockerfile
echo "RUN apt-get update && apt-get install -y --no-install-recommends sudo" >> .cqfd/docker/Dockerfile

################################################################################
# cqfd run should be happy using sudo.
################################################################################
jtest_prepare "cqfd run with sudo"
if "$cqfd" init && "$cqfd" run true \
	| awk -v rc=1 '/Using "sudo" to execute command/ { rc=0 } 1; END {exit rc}'; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Restore initial Dockerfile.
################################################################################
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
"$cqfd" init
