#!/usr/bin/env bash
#
# validate the behavior of custom image

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
cqfd_docker="${CQFD_DOCKER:-docker}"

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.old
cp -f .cqfd/docker/Dockerfile.init_custom_image .cqfd/docker/Dockerfile
cp -f .cqfdrc .cqfdrc.old
cp -f cqfdrc-custom_image .cqfdrc
custom_img_name="cqfd_test_custom_image_$RANDOM$RANDOM"
sed -i -e "s!^custom_img_name=.*\$!custom_img_name='$custom_img_name'!" .cqfdrc

################################################################################
# 'cqfd init' with custom_img_name
################################################################################
jtest_log info "$cqfd_docker registry contains NO image named: $custom_img_name"
if "$cqfd_docker" inspect "$custom_img_name" &>/dev/null; then
	jtest_log info "$cqfd_docker registry contains image named: $custom_img_name, removing..."
	"$cqfd_docker" rmi "$custom_img_name"
fi

jtest_prepare "cqfd init works using custom_img_name=$custom_img_name"
if "$cqfd" init && "$cqfd" run "true"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "$cqfd_docker registry contains image named: $custom_img_name"
if "$cqfd_docker" inspect "$custom_img_name" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
"$cqfd_docker" rmi "$custom_img_name"

################################################################################
# Restore initial .cqfdrc and Dockerfile
################################################################################
mv -f .cqfdrc.old .cqfdrc
mv -f .cqfd/docker/Dockerfile.old .cqfd/docker/Dockerfile
