#!/usr/bin/env bash
#
# validate the behavior of init command with extra hosts in build environment variable

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd with docker_build_args in config"
# setup -- add the command and docker_build_args option to configs
echo "RUN cp /etc/hosts /tmp/hosts" >>"$TDIR/.cqfd/docker/Dockerfile"
sed '/\[build\]/adocker_build_args="--add-host testhost:1.2.3.4"'\
    -i "$TDIR/.cqfdrc"
output=$("$cqfd" init; "$cqfd" run cat /tmp/hosts; exit 0)
if [[ "$output" == *"1.2.3.4"*"testhost"* ]]; then
    jtest_result pass
else
    jtest_result fail
fi

# teardown -- clear the command and docker_build_args option from config
sed '/\[build\]/{n;d}' -i "$TDIR/.cqfdrc"
sed '$d' -i "$TDIR/.cqfd/docker/Dockerfile"
