#!/usr/bin/env bash
#
# validate the behavior of cqfd with tag

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
cqfd_docker="${CQFD_DOCKER:-docker}"

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.old
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.old
cp -f .cqfdrc .cqfdrc.old
cp -f cqfdrc-tag .cqfdrc

################################################################################
# 'cqfd init' creates image with tag
################################################################################
random="$RANDOM$RANDOM"
tag="cqfd-%Un-%Po-%Pn-%Dh-%Bd-$random"
sed -i -e "s!^tag=.*\$!tag='$tag'!" .cqfdrc
# shellcheck disable=SC2001
un="$(sed 's/[^0-9a-zA-Z\-]/_/g' <<<"$USER")"
dh="$(sha256sum .cqfd/docker/Dockerfile | cut -b 1-7)"
image="cqfd-$un-cqfd-test-$dh-docker-$random"
if "$cqfd_docker" inspect "$image" &>/dev/null; then
	jtest_log info "$cqfd_docker registry contains image named: $image, removing..."
	"$cqfd_docker" rmi "$image"
fi

jtest_prepare "cqfd init with tag $tag builds templated image $image"
if "$cqfd" init && \
   "$cqfd_docker" inspect "$image" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
"$cqfd_docker" rmi "$image"

tag="cqfd-%Un-%Po-%Pn-%DH-%Bd-$random"
sed -i -e "s!^tag=.*\$!tag='$tag'!" .cqfdrc
dh="$(sha256sum .cqfd/centos/Dockerfile | cut -b 1-64)"
image="cqfd-$un-cqfd-test-$dh-centos-$random"
if "$cqfd_docker" inspect "$image" &>/dev/null; then
	jtest_log info "$cqfd_docker registry contains image named: $image, removing..."
	"$cqfd_docker" rmi "$image"
fi

jtest_prepare "cqfd init with tag $tag and distro build templated image $image"
sed -i -e "s/\[build\]/[build]\ndistro='centos'/" .cqfdrc
if "$cqfd" init && \
   "$cqfd_docker" inspect "$image" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
"$cqfd_docker" rmi "$image"

################################################################################
# Restore initial .cqfdrc and Dockerfile
################################################################################
mv -f .cqfdrc.old .cqfdrc
mv -f .cqfd/docker/Dockerfile.old .cqfd/docker/Dockerfile
