#!/bin/bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
flavor="foo"

cd $TDIR/

cqfdrc_old=`mktemp`
cp -f .cqfdrc $cqfdrc_old
sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" .cqfdrc

jtest_prepare "cqfd init using '$flavor' flavor"
if $cqfd -b $flavor init &&
   $cqfd -b $flavor run "grep '^NAME=' /etc/*release" | grep -q 'NAME="CentOS Linux"'; then
	jtest_result pass
else
	jtest_result fail
fi

mv -f $cqfdrc_old .cqfdrc

jtest_prepare "cqfd init without flavor"
if $cqfd init &&
   $cqfd run "grep '^NAME=' /etc/*release" | grep -q 'NAME="Ubuntu"'; then
	jtest_result pass
else
	jtest_result fail
fi
