#!/usr/bin/env bash
#
# validate the behavior of run command with flavors

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
flavor="foo"

cd "$TDIR/" || exit 1

# First pass: build a simple flavor
# Second pass: override flavor build with an additional command

for i in 0 1; do
	jtest_log info "run cqfd with a given '$flavor' flavor, pass $i"

	if [ "$i" = "0" ]; then
		test_file=$flavor
		jtest_prepare "cqfd run build cmd for '$flavor' flavor"
		"$cqfd" -b "$flavor" run
	else
		test_file="file.$RANDOM"
		jtest_prepare "cqfd run and override with additional cmd"
		"$cqfd" -b $flavor run touch "$test_file"
	fi

	# shellcheck disable=SC2181
	if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
		jtest_result pass
	else
		jtest_log fatal "failed or test file not present after execution"
		jtest_result fail
	fi
	rm -f "$test_file"
done
