#!/bin/bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/


################################################################################
# 'cqfd run' sets HOME environment variable for the local user
################################################################################
jtest_prepare "run cqfd sets HOME environment variable for the local user"
result=$($cqfd run 'echo -n $HOME')

if [ "$result" = "$HOME" ]; then
	jtest_result pass
else
	jtest_result fail
fi


################################################################################
# 'cqfd run' does not override HOME environment explicitely set via
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't override HOME env when set via CQFD_EXTRA_RUN_ARGS"
val1="value-$RANDOM"
val2="value-$RANDOM"

result=$(CQFD_EXTRA_RUN_ARGS="-e FOO=$val1 -e HOME=$val2" \
	$cqfd run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not override HOME environment when it is the only entry in
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't override HOME env when the only entry in CQFD_EXTRA_RUN_ARGS"
val1="value-$RANDOM"

result=$(CQFD_EXTRA_RUN_ARGS="-e HOME=$val1" \
	$cqfd run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not confuse JAVA_HOME and the like with HOME when set via
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't confuse JAVA_HOME and the like with HOME"
val1="value-$RANDOM"
val2="value-$RANDOM"

result=$(CQFD_EXTRA_RUN_ARGS="-e JAVA_HOME=$val1 -e HOME=$val2" \
	$cqfd run 'echo -n $JAVA_HOME $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi
