#!/usr/bin/env bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
flavor="foo"
test_file=$flavor
test_run_c_file="test_run_c.txt"

cd $TDIR/

# concatenate flavor build with an additional option
jtest_log info "run cqfd run -c with a given '$flavor' flavor"

if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
	jtest_log fatal "$test_file or $test_run_c_file already present before test"
	rm -f $test_file
	rm -f $test_run_c_file
	continue
fi

jtest_prepare "build cmd for '$flavor' flavor and concatenate with an additional option"
$cqfd -b $flavor run -c --debug >> $test_run_c_file

# at the end of this test, $test_run_c_file is populated
if ! grep -qw "target \`foo'" $test_run_c_file; then
	jtest_log fatal "$test_run_c_file not present after test"
	jtest_result fail
	rm -f $test_run_c_file
	continue
fi

# at the end of either test, $test_file is populated
if ! grep -qw "cqfd" $test_file; then
	jtest_log fatal "$test_file not present after test"
	jtest_result fail
	rm -f $test_file
	continue
else
	jtest_result pass
fi

rm -f $test_file
rm -f $test_run_c_file
