#!/usr/bin/env bash
#
# validate the behavior of run command with HOME environment variable

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
cqfd_docker="${CQFD_DOCKER:-docker}"

cd "$TDIR/" || exit 1

cqfdrc_old=$(mktemp)
cp -f .cqfdrc "$cqfdrc_old"

################################################################################
# 'cqfd run' sets HOME environment variable for the local user
################################################################################
jtest_prepare "run cqfd sets HOME environment variable for the local user"
# shellcheck disable=SC2016
result=$("$cqfd" run 'echo -n $HOME')

if [ "$result" = "$HOME" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not override HOME environment explicitely set via
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't override HOME env when set via CQFD_EXTRA_RUN_ARGS"
val1="value-$RANDOM"
val2="value-$RANDOM"

# shellcheck disable=SC2016
result=$(CQFD_EXTRA_RUN_ARGS="-e FOO=$val1 -e HOME=$val2" \
	"$cqfd" run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not override HOME environment when it is the only entry in
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't override HOME env when the only entry in CQFD_EXTRA_RUN_ARGS"
val1="value-$RANDOM"

# shellcheck disable=SC2016
result=$(CQFD_EXTRA_RUN_ARGS="-e HOME=$val1" \
	"$cqfd" run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not confuse JAVA_HOME and the like with HOME when set via
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run doesn't confuse JAVA_HOME and the like with HOME"
val1="value-$RANDOM"
val2="value-$RANDOM"

# shellcheck disable=SC2016
result=$(CQFD_EXTRA_RUN_ARGS="-e JAVA_HOME=$val1 -e HOME=$val2" \
	"$cqfd" run 'echo -n $JAVA_HOME $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# The container's user directory has been created with the right home
# directory.
################################################################################
jtest_prepare "the user's home in passwd == \$HOME"

if [ "$cqfd_docker" = "podman" ]; then
	jtest_result skip
else
	passwd_home=$("$cqfd" run "grep ^$(whoami): /etc/passwd |cut -d: -f6")
	user_home=$("$cqfd" run "echo \$HOME")
	if [ "$passwd_home" = "$user_home" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# 'cqfd run' does not override HOME environment explicitly set via
# docker_run_args
################################################################################
jtest_prepare "run doesn't override HOME env when set via docker_run_args"
val1="value-$RANDOM"
val2="value-$RANDOM"
cat "$cqfdrc_old" - <<EOF >.cqfdrc
docker_run_args="--env FOO=$val1 --env HOME=$val2"
EOF

# shellcheck disable=SC2016
result=$("$cqfd" run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not override HOME environment when it is the only entry in
# docker_run_args
################################################################################
jtest_prepare "run doesn't override HOME env when the only entry in docker_run_args"
val1="value-$RANDOM"
cat "$cqfdrc_old" - <<EOF >.cqfdrc
docker_run_args="--env HOME=$val1"
EOF

# shellcheck disable=SC2016
result=$("$cqfd" run 'echo -n $FOO $HOME' | grep value)

if [ "$result" = "$val1" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd run' does not confuse JAVA_HOME and the like with HOME when set via
# docker_run_args
################################################################################
jtest_prepare "run doesn't confuse JAVA_HOME and the like with HOME"
val1="value-$RANDOM"
val2="value-$RANDOM"
cat "$cqfdrc_old" - <<EOF >.cqfdrc
docker_run_args="--env JAVA_HOME=$val1 --env HOME=$val2"
EOF

# shellcheck disable=SC2016
result=$("$cqfd" run 'echo -n $JAVA_HOME $HOME' | grep value)

if [ "$result" = "$val1 $val2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# restore .cqfdrc
################################################################################
mv -f "$cqfdrc_old" .cqfdrc
