#!/usr/bin/env bash
#
# validate the behavior of run command with extra run environment variable

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/"

################################################################################
# 'cqfd run' passes environment variables to the container when using
# CQFD_EXTRA_RUN_ARGS
################################################################################
jtest_prepare "run cqfd with extra environment variables"

val1="value-$RANDOM"
val2="value-$RANDOM"

# shellcheck disable=SC2016
result=$(CQFD_EXTRA_RUN_ARGS="-e FOO=$val1 -e BAR=$val2" \
	"$cqfd" run 'echo -n $FOO $BAR' | grep value)

if [ "$result" = "$val1 $val2" ]; then
    jtest_result pass
else
    jtest_result fail
fi
