#!/usr/bin/env bash
#
# validate the behavior of init with alternate file and external directory

. "$(dirname "$0")"/jtest.inc "$1"

cd "$TDIR/" || exit 1

################################################################################
# First, move every local cqfd files into an external directory and use
# alternate filenames
################################################################################
extdir="external/dir"
mkdir -p "$extdir"
mv .cqfd "$extdir/cqfd"
mv .cqfdrc "$extdir/cqfdrc"
cqfd="$TDIR/$extdir/cqfd/cqfd"

################################################################################
# 'cqfd init' without local files should fail
################################################################################
jtest_prepare "cqfd init without local files should fail"
if ! "$cqfd" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using filenames
# should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using filenames should work"
if "$cqfd" -C "$extdir" -d cqfd -f cqfdrc init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using relative filenames should work"
if "$cqfd" -d "$extdir/cqfd" -f "$extdir/cqfdrc" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using absolute filenames should work"
if "$cqfd" -d "$PWD/$extdir/cqfd" -f "$PWD/$extdir/cqfdrc" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# restore local cqfd files
################################################################################
mv "$extdir/cqfdrc" .cqfdrc
mv "$extdir/cqfd" .cqfd
rmdir -p "$extdir"
