#!/usr/bin/env bash
#
# validate the behavior of init command with flavors

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
flavor="foo"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd init' with different flavor makes a different container
################################################################################
cqfdrc_old=$(mktemp)
cp -f .cqfdrc "$cqfdrc_old"
sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" .cqfdrc

jtest_prepare "cqfd init using '$flavor' flavor"
if "$cqfd" -b "$flavor" --reinit run "grep '^NAME=' /etc/*release" | grep -q 'NAME="CentOS Linux"'; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' with invalid flavor should fail
################################################################################
flavorPart="${flavor:0:2}"
jtest_prepare "cqfd init using part of '$flavor' flavor should fail"
if ! "$cqfd" -b "$flavorPart" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' without flavor generates our regular container
################################################################################
mv -f "$cqfdrc_old" .cqfdrc

jtest_prepare "cqfd init without flavor"
if "$cqfd" --reinit run "grep '^NAME=' /etc/*release" | grep -q 'NAME="Ubuntu"'; then
	jtest_result pass
else
	jtest_result fail
fi
