#!/bin/bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
test_file="build.txt"

cd $TDIR

# Here we test cqfd run, which is also invoked without any argument
for i in 0 1; do
	# Data set shall produce build.txt:

	jtest_log info "run cqfd without any argument, pass $i"

	if [ -f "$test_file" ]; then
		jtest_log fatal "$test_file already present before test"
		rm -f $test_file
		continue
	fi

	if [ "$i" = "1" ]; then
		jtest_prepare "running cqfd run for pass $f"
		$cqfd run
	else
		jtest_prepare "running cqfd run without argument for pass $f"
		$cqfd
	fi

	# at the end of either test, $test_file is populated
	if ! grep -qw "cqfd" $test_file; then
		jtest_log fatal "$test_file not present after test"
		jtest_result fail
		continue
	else
		jtest_result pass
	fi

	rm -f $test_file
done
