#!/usr/bin/env bash

. "$(dirname $0)"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

jtest_prepare "cqfd can run from a project's sub-directory"

pushd "$TDIR" >/dev/null || exit 1

# Create and enter a dummy sub-directory tree
sub_dir="dir with space/b/c/d/e"
mkdir -p "$sub_dir"
pushd "$sub_dir" >/dev/null || exit 1

# the two paths should be identical
p1=$(pwd | strings)
p2=$($cqfd run pwd | strings)

if [ "$p1" = "$p2" ]; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
popd >/dev/null || exit 1
rm -rf aaa
