#!/usr/bin/env bash
#
# validate the behavior of custom image

. "$(dirname $0)"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

# create a temporary directory
TEST_DIR=$(mktemp -d -t cqfd-test-XXXXXX)
cd "$TEST_DIR"/

################################################################################
# 'cqfd init' with custom_img_name
################################################################################
custom_image_1="cqfd_test_custom_image_1_$RANDOM$RANDOM"

# Test .cqfdrc
cat >.cqfdrc <<EOF
[project]
org="cqfd"
name="custom-image"
custom_img_name="$custom_image_1"

[build]
command="true"
EOF

# Test dockerfile
mkdir -p .cqfd/docker
echo "FROM ubuntu:24.04" > .cqfd/docker/Dockerfile

jtest_prepare "docker registry contains NO image named: $custom_image_1"
if docker inspect "$custom_image_1" &>/dev/null; then
	jtest_result fail
else
	jtest_result pass
fi

jtest_prepare "cqfd init works using custom_img_name=$custom_image_1"
if $cqfd init && $cqfd run "true"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "docker registry contains image named: $custom_image_1"
if docker inspect "$custom_image_1" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cleanup
################################################################################
rm -rf "$TEST_DIR"
