#!/usr/bin/env bash
#
# validate the behavior of run command that do not preserve arguments

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/

jtest_prepare "cqfd run do not preserve the arguments"
if ( ! $cqfd run /bin/sh -c 'printf "0=$0,*=$*,#=$#"' zero one two three ) \
           | grep "0=sh,\*=,#=0"; then
	jtest_result pass
else
	jtest_result fail
fi
