#!/usr/bin/env bash
#
# validate the behavior of run with Dockerfile

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

# backup Dockerfile
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "cqfd run using a Dockerfile with entrypoint should success"
cat <<EOF >>.cqfd/docker/Dockerfile
ENTRYPOINT ["false"]
EOF
if "$cqfd" init && "$cqfd" run; then
	jtest_result pass
else
	jtest_result fail
fi

# restore Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
"$cqfd" init
