#!/bin/bash

. `dirname $0`/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/

jtest_prepare "cqfd release"
if $cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd-undefined.tar.xz was generated"

if tar tf cqfd-undefined.tar.xz >/dev/null 2>&1; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f cqfd-undefined.tar.xz

jtest_prepare "release.archive templating"

# append this to the [release] section
export CTEST=foobar
d3=`date --rfc-3339='date'`
echo 'archive=cqfd-%D3-$CTEST.tar.xz' >> .cqfdrc

$cqfd release

if tar tf cqfd-$d3-foobar.tar.xz >/dev/null 2>&1; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f cqfd-$gh-foobar.tar.xz
