#!/usr/bin/env bash
#
# validate the behavior of shell command

set -o pipefail

unset CQFD_SHELL

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

jtest_prepare "cqfd shell should succeed with no stdin"
if "$cqfd" shell </dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should read commands from stdin"
if ( ! "$cqfd" shell <<<"tty" ) | grep "not a tty"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should preserve the arguments"
# shellcheck disable=SC2016
if "$cqfd" shell -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "0=zero,\*=one two three,#=3$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should fail with 127 and '/bin/non-existant-shell: command not found'"
if CQFD_SHELL=/bin/non-existant-shell "$cqfd" shell <<<"tty" \
	| grep -q '/bin/non-existant-shell: command not found';
                                      test "${PIPESTATUS[0]}" -eq 127; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd sh should succeed and use sh"
# shellcheck disable=SC2016
if "$cqfd" sh <<<'printf "$0"' | grep -q "^sh$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd bash should succeed and use bash"
# shellcheck disable=SC2016
if "$cqfd" bash <<<'printf "$0"' | grep -q "^bash$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd dash should succeed and use dash"
# shellcheck disable=SC2016
if "$cqfd" dash <<<'printf "$0"' | grep -q "^dash$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd zsh should fail with 127 and 'zsh: command not found'"
# shellcheck disable=SC2016
if "$cqfd" zsh 2>&1 <<<'printf "$0"' | grep -q 'zsh: command not found';
   test "${PIPESTATUS[0]}" -eq 127; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable to run shell script"
if "$cqfd" shell ./whereami.sh 2>&1 | grep '^Ubuntu .* LTS$'; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd bash is usable to run shell script"
if "$cqfd" bash ./whereami.sh 2>&1 | grep '^Ubuntu .* LTS$'; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable as a shell interpreter script"
if PATH="$TDIR/.cqfd:$PATH"; ./whereami.sh 2>&1 | grep '^Ubuntu .* LTS$'; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable as a shell interpreter in binaries"
if ! command -v make 2>/dev/null; then
	jtest_result skip
else
	if PATH="$TDIR/.cqfd:$PATH"; make whereami 2>&1 | grep '^Ubuntu .* LTS$'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi
