#!/usr/bin/env bash
#
# validate the behavior of shell command

set -o pipefail

unset CQFD_SHELL

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd $TDIR/

jtest_prepare "cqfd shell should succeed with no stdin"
if $cqfd shell </dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should read commands from stdin"
if ( ! $cqfd shell <<<"tty" ) | grep "not a tty"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should preserve the arguments"
if $cqfd shell -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "0=zero,\*=one two three,#=3$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should fail with 127 if \$CQFD_SHELL is not found"
if CQFD_SHELL=/bin/non-existant-shell $cqfd shell <<<"tty";
                                      test "$?" -eq 127; then
	jtest_result pass
else
	jtest_result fail
fi
