#!/usr/bin/env bash
#
# validate the behavior of destroy command

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd destroy' with a proper .cqfdrc should pass
################################################################################
jtest_prepare "run cqfd destroy"
if "$cqfd" destroy; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd destroy' with a nonexistent Dockerfile should fail
################################################################################
cqfdrc_old=$(mktemp)
jtest_prepare "destroy with a nonexisting dockerfile shall fail"
cp -f .cqfdrc "$cqfdrc_old"
sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
if ! "$cqfd" destroy; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd destroy' with a proper Dockerfile should fail
################################################################################
jtest_prepare "run cqfd destroy with an other Dockerfile"
sed -i -e "s/thisshouldfail/centos/" .cqfdrc
if "$cqfd" init && "$cqfd" destroy; then
	jtest_result pass
else
	jtest_result fail
fi
# restore cqfdrc
mv -f "$cqfdrc_old" .cqfdrc

################################################################################
# 'cqfd destroy' with an already destroyed image should fail
################################################################################
jtest_prepare "destroy an already destroyed image shall fail"
if ! "$cqfd" destroy; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd destroy' with CQFD_EXTRA_RMI_ARGS should succeed
################################################################################
jtest_prepare "destroy using CQFD_EXTRA_RMI_ARGS"
if CQFD_EXTRA_RMI_ARGS="--force" "$cqfd" destroy; then
	jtest_result pass
else
	jtest_result fail
fi
