#!/usr/bin/env bash
#
# validate the behavior of ls command

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR"/.cqfd/cqfd

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd ls' should list build containers
################################################################################
jtest_prepare "run cqfd ls"
if "$cqfd" ls | grep "^cqfd_$USER\_cqfd_test_";
   test "${PIPESTATUS[0]}" -eq 0 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi
