.PHONY: all clean build

all:
	@echo "make foo or bar!"


foo:
	@echo making foo
	@echo cqfd >foo

bar:
	@echo making bar
	@echo cqfd >bar

build:
	@echo cqfd >build.txt

clean:
	@rm -f foo bar build.txt
