name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run linting
      run: make check

    - name: Run tests for docker
      run: make tests

    - name: Run tests for podman
      run: CQFD_DOCKER_EXECUTABLE=podman make tests
